FROM python:3.8
WORKDIR /app

# COPY api/requirements.txt api/api.py api/cp.py api/.flaskenv ./
COPY api/. ./
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "api:app"]